// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Review.Persistence;

#nullable disable

namespace Review.Persistence.Migrations
{
    [DbContext(typeof(ReviewDbContext))]
    partial class ReviewDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Review.Domain.Articles.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JournalId")
                        .HasColumnType("int");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubmittedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JournalId");

                    b.HasIndex("SubmittedById");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("Review.Domain.Articles.ArticleActor", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("TypeDiscriminator")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValue("AUT");

                    b.HasKey("ArticleId", "PersonId", "TypeDiscriminator");

                    b.HasIndex("PersonId");

                    b.HasIndex("ArticleId", "PersonId", "Role");

                    b.ToTable("ArticleActor");

                    b.HasDiscriminator<string>("TypeDiscriminator").HasValue("ArticleActor");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Review.Domain.Articles.ReviewerSpecialization", b =>
                {
                    b.Property<int>("JournalId")
                        .HasColumnType("int");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("int");

                    b.HasKey("JournalId", "ReviewerId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("ReviewerSpecialization");
                });

            modelBuilder.Entity("Review.Domain.Assets.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.ComplexProperty<Dictionary<string, object>>("File", "Review.Domain.Assets.Asset.File#File", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("FileServerId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)");

                            b1.Property<string>("OriginalName")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasComment("Original full file name, with extension");

                            b1.Property<long>("Size")
                                .HasColumnType("bigint")
                                .HasComment("Size of the file in kilobytes");

                            b1.ComplexProperty<Dictionary<string, object>>("Extension", "Review.Domain.Assets.Asset.File#File.Extension#FileExtension", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(8)
                                        .HasColumnType("nvarchar(8)")
                                        .HasColumnName("File_Extension");
                                });

                            b1.ComplexProperty<Dictionary<string, object>>("Name", "Review.Domain.Assets.Asset.File#File.Name#FileName", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(64)
                                        .HasColumnType("nvarchar(64)")
                                        .HasColumnName("File_Name")
                                        .HasComment("Final name of the file after renaming");
                                });
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Name", "Review.Domain.Assets.Asset.Name#AssetName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("Name");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("Type");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("Review.Domain.Assets.AssetTypeDefinition", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("DefaultFileExtension")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasDefaultValue("pdf");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnOrder(2);

                    b.Property<byte>("MaxAssetCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<byte>("MaxFileSizeInMB")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnOrder(1);

                    b.ComplexProperty<Dictionary<string, object>>("AllowedFileExtensions", "Review.Domain.Assets.AssetTypeDefinition.AllowedFileExtensions#FileExtensions", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Extensions")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("AllowedFileExtensions");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AssetTypeDefinition");
                });

            modelBuilder.Entity("Review.Domain.Invitations.ReviewInvitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("SentById")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.ComplexProperty<Dictionary<string, object>>("Email", "Review.Domain.Invitations.ReviewInvitation.Email#EmailAddress", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("Email");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Token", "Review.Domain.Invitations.ReviewInvitation.Token#InvitationToken", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("Token");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("SentById");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("Review.Domain.Shared.Journal", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Journals");
                });

            modelBuilder.Entity("Review.Domain.Shared.Person", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<string>("Affiliation")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasComment("Institution or organization they are associated with when they conduct their research.");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Honorific")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TypeDiscriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.ComplexProperty<Dictionary<string, object>>("Email", "Review.Domain.Shared.Person.Email#EmailAddress", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("Email");
                        });

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Persons");

                    b.HasDiscriminator<string>("TypeDiscriminator").HasValue("Person");

                    b
                        .UseTphMappingStrategy()
                        .HasAnnotation("RawSql:Index", "CREATE UNIQUE INDEX IX_Person_Email_TypeDiscriminator ON Person (Email, TypeDiscriminator)");
                });

            modelBuilder.Entity("Review.Domain.Articles.ArticleAuthor", b =>
                {
                    b.HasBaseType("Review.Domain.Articles.ArticleActor");

                    b.Property<string>("ContributionAreas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("ArticleAuthor");
                });

            modelBuilder.Entity("Review.Domain.Articles.Author", b =>
                {
                    b.HasBaseType("Review.Domain.Shared.Person");

                    b.Property<string>("Degree")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasComment("The highest academic degree of the author, e.g., PhD, MD, etc.");

                    b.Property<string>("Discipline")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("The scientific discipline of the author, e.g., Computer Science, Biology, etc.");

                    b.HasDiscriminator().HasValue("Author");
                });

            modelBuilder.Entity("Review.Domain.Reviewers.Reviewer", b =>
                {
                    b.HasBaseType("Review.Domain.Shared.Person");

                    b.HasDiscriminator().HasValue("Reviewer");
                });

            modelBuilder.Entity("Review.Domain.Articles.Editor", b =>
                {
                    b.HasBaseType("Review.Domain.Reviewers.Reviewer");

                    b.HasDiscriminator().HasValue("Editor");
                });

            modelBuilder.Entity("Review.Domain.Articles.Article", b =>
                {
                    b.HasOne("Review.Domain.Shared.Journal", "Journal")
                        .WithMany("Articles")
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Review.Domain.Shared.Person", "SubmittedBy")
                        .WithMany()
                        .HasForeignKey("SubmittedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Journal");

                    b.Navigation("SubmittedBy");
                });

            modelBuilder.Entity("Review.Domain.Articles.ArticleActor", b =>
                {
                    b.HasOne("Review.Domain.Articles.Article", "Article")
                        .WithMany("Actors")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Review.Domain.Shared.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Review.Domain.Articles.ReviewerSpecialization", b =>
                {
                    b.HasOne("Review.Domain.Shared.Journal", "Journal")
                        .WithMany("Reviewers")
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Review.Domain.Reviewers.Reviewer", "Reviewer")
                        .WithMany("Specializations")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journal");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("Review.Domain.Assets.Asset", b =>
                {
                    b.HasOne("Review.Domain.Articles.Article", "Article")
                        .WithMany("Assets")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Review.Domain.Assets.AssetTypeDefinition", "TypeDefinition")
                        .WithMany()
                        .HasForeignKey("Type")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("TypeDefinition");
                });

            modelBuilder.Entity("Review.Domain.Invitations.ReviewInvitation", b =>
                {
                    b.HasOne("Review.Domain.Articles.Article", null)
                        .WithMany("Invitations")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Review.Domain.Shared.Person", "SentBy")
                        .WithMany()
                        .HasForeignKey("SentById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SentBy");
                });

            modelBuilder.Entity("Review.Domain.Articles.Article", b =>
                {
                    b.Navigation("Actors");

                    b.Navigation("Assets");

                    b.Navigation("Invitations");
                });

            modelBuilder.Entity("Review.Domain.Shared.Journal", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("Reviewers");
                });

            modelBuilder.Entity("Review.Domain.Reviewers.Reviewer", b =>
                {
                    b.Navigation("Specializations");
                });
#pragma warning restore 612, 618
        }
    }
}
