// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Submission.Persistence;

#nullable disable

namespace Submission.Persistence.Migrations
{
    [DbContext(typeof(SubmissionDbContext))]
    [Migration("20260319125649_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Submission.Domain.Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JournalId")
                        .HasColumnType("int");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubmittedById")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JournalId");

                    b.HasIndex("SubmittedById");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("Submission.Domain.Entities.ArticleActor", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValue("AUT");

                    b.Property<string>("TypeDiscriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("ArticleId", "PersonId", "Role");

                    b.HasIndex("PersonId");

                    b.ToTable("ArticleActors");

                    b.HasDiscriminator<string>("TypeDiscriminator").HasValue("ArticleActor");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Submission.Domain.Entities.ArticleStageTransition", b =>
                {
                    b.Property<string>("CurrentStage")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ActionType")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DestinationStage")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CurrentStage", "ActionType", "DestinationStage");

                    b.ToTable("ArticleStageTransition", (string)null);

                    b.HasData(
                        new
                        {
                            CurrentStage = "Created",
                            ActionType = "AssignAuthor",
                            DestinationStage = "Created"
                        },
                        new
                        {
                            CurrentStage = "Created",
                            ActionType = "UploadAsset",
                            DestinationStage = "Created"
                        },
                        new
                        {
                            CurrentStage = "Created",
                            ActionType = "SubmitDraft",
                            DestinationStage = "Submitted"
                        },
                        new
                        {
                            CurrentStage = "Submitted",
                            ActionType = "ApproveDraft",
                            DestinationStage = "InitialApproved"
                        },
                        new
                        {
                            CurrentStage = "Submitted",
                            ActionType = "RejectDraft",
                            DestinationStage = "InitialRejected"
                        },
                        new
                        {
                            CurrentStage = "InitialRejected",
                            ActionType = "SubmitDraft",
                            DestinationStage = "Submitted"
                        });
                });

            modelBuilder.Entity("Submission.Domain.Entities.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ComplexProperty<Dictionary<string, object>>("File", "Submission.Domain.Entities.Asset.File#File", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("FileServerId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)");

                            b1.Property<string>("OriginalName")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasComment("Original full file name ´with extension");

                            b1.Property<long>("Size")
                                .HasColumnType("bigint")
                                .HasComment("File size in bytes");

                            b1.ComplexProperty<Dictionary<string, object>>("Extension", "Submission.Domain.Entities.Asset.File#File.Extension#FileExtension", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(8)
                                        .HasColumnType("nvarchar(8)")
                                        .HasColumnName("File_Extension");
                                });

                            b1.ComplexProperty<Dictionary<string, object>>("Name", "Submission.Domain.Entities.Asset.File#File.Name#FileName", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(64)
                                        .HasColumnType("nvarchar(64)")
                                        .HasColumnName("File_Name")
                                        .HasComment("Final name of the file after renaming");
                                });
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Name", "Submission.Domain.Entities.Asset.Name#AssetName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("Name");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("Submission.Domain.Entities.AssetTypeDefinition", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("DefaultFileExtension")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasDefaultValue("pdf");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxAssetCount")
                        .HasColumnType("int");

                    b.Property<byte>("MaxFileSizeInMB")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)5);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnOrder(1);

                    b.ComplexProperty<Dictionary<string, object>>("AllowedFileExtensions", "Submission.Domain.Entities.AssetTypeDefinition.AllowedFileExtensions#FileExtensions", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Extensions")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("AllowedFileExtensions");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AssetTypes");
                });

            modelBuilder.Entity("Submission.Domain.Entities.Journal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Journals");
                });

            modelBuilder.Entity("Submission.Domain.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Affiliation")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasComment("Institution or organization they are associated with when they conduct their research");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Title")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TypeDiscriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.ComplexProperty<Dictionary<string, object>>("Email", "Submission.Domain.Entities.Person.Email#EmailAddress", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("Email");
                        });

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("People");

                    b.HasDiscriminator<string>("TypeDiscriminator").HasValue("Person");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Submission.Domain.Entities.ArticleAuthor", b =>
                {
                    b.HasBaseType("Submission.Domain.Entities.ArticleActor");

                    b.Property<string>("ContributionAreas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("ArticleAuthor");
                });

            modelBuilder.Entity("Submission.Domain.Entities.Author", b =>
                {
                    b.HasBaseType("Submission.Domain.Entities.Person");

                    b.Property<string>("Degree")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("The highest academic degree of the author, e.g., PhD, MD, etc.");

                    b.Property<string>("Discipline")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("The scientific discipline of the author, e.g., Computer Science, Biology, etc.");

                    b.HasDiscriminator().HasValue("Author");
                });

            modelBuilder.Entity("Submission.Domain.Entities.Article", b =>
                {
                    b.HasOne("Submission.Domain.Entities.Journal", "Journal")
                        .WithMany("Articles")
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Submission.Domain.Entities.Person", "SubmittedBy")
                        .WithMany()
                        .HasForeignKey("SubmittedById");

                    b.Navigation("Journal");

                    b.Navigation("SubmittedBy");
                });

            modelBuilder.Entity("Submission.Domain.Entities.ArticleActor", b =>
                {
                    b.HasOne("Submission.Domain.Entities.Article", "Article")
                        .WithMany("Actors")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Submission.Domain.Entities.Person", "Person")
                        .WithMany("ArticleActors")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Submission.Domain.Entities.Asset", b =>
                {
                    b.HasOne("Submission.Domain.Entities.Article", "Article")
                        .WithMany("Assets")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Submission.Domain.Entities.Article", b =>
                {
                    b.Navigation("Actors");

                    b.Navigation("Assets");
                });

            modelBuilder.Entity("Submission.Domain.Entities.Journal", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("Submission.Domain.Entities.Person", b =>
                {
                    b.Navigation("ArticleActors");
                });
#pragma warning restore 612, 618
        }
    }
}
